# Generated by Django 3.2.1 on 2021-05-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='dete_added',
            new_name='date_added',
        ),
    ]
